CC:= g++

CFLAGS:= -g -std=c++11

LIB:=src/AbstractHex.cpp src/HexVector.cpp src/HexAdapter.cpp src/HexArray1D.cpp

MAIN= src/main.cpp

program:execute
	./a.out
execute:
	$(CC) $(CFLAGS) $(MAIN) $(LIB)

